8 créer un rendez vous
jessyjr97/carlmelanie-masso-webApp pull request #25
Opened 2019-03-30 04:16 UTC by jessyjr97

2019-03-30 04:22 UTC, yjacques940 requested changes
Il faut s'assurer que toutes les autres pages foncitonnent encore, vérifier que le rebase fonctionne bien

2019-04-03 12:46 UTC, yjacques940 requested changes
- On devrait avoir le menu pour accéder à la page des rendez-vous dans la page d'accueil
-Mettre un titre pour la page Liste des rendez-vous
-Changer le message du bouton n'Est pas vraiment clair, peut être changer sa couleur pour gris, pour dire qu'on ne peut pas recliquer dessus?
Les noms des colonnes ne représentent pas le data qui est à l'intérieur 👎 
![image](https://user-images.githubusercontent.com/40217275/55479809-dc68a880-55ec-11e9-8ae2-6d944fbb923c.png)

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/controlleurs/Controlleurs.php
>          echo 'il n y a aucune donnee d entree';
S'il y a d'autres points à modif, pourrait tu modif ce message pour qu'il soit localizable avec un message plus clair svp? :P

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/controlleurs/Controlleurs.php
> +            'DurationTime' => htmlentities($_POST['appointmentLength']),
'appointmentDuration' serait-il plus approprié?

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/controlleurs/Controlleurs.php
> +            echo  'success';
Est-ce que ca vaut la peine de les mettre localizable? (lui et les echo plus bas)

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/lang/en.json
> +  "Appointment-Duration":"Length",
on utilise déjà duration, on devrait continuer à utiliser duration au lieu de length

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/OnClick.html
> +/*
Commentaire pas utliisé?

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/OnClick.html
> +            $('#btn_makeAppointment').append('  <span class="fa fa-cog fa-spin"></span>');
Normal qu'il y ait 2 espaces avant le span?

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/OnClick.html
> +                var appointmentLength = document.getElementById('appointmentLength').value;
duration

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/OnClick.html
> +                if (!appointmentLength){
duration

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/OnClick.html
> +                    alert('Veuillez sélectionner la durée du rendez-vous');
localize?

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/OnClick.html
> +                            appointmentLength: appointmentLength,
duration

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/OnClick.html
> +                                $('#btn_makeAppointment').html('Prendre un rendez-vous');
localize?

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/OnClick.html
> +                                $('#btn_makeAppointment').html('Réservé avec succès!');
localize?

2019-04-03 12:46 UTC, yjacques940 commented on webapp/src/views/appointment_creator.php
> +                                                <th><?php //echo $phoneNumber->idPhoneType; ?></th>
Commentaire

2019-04-03 14:12 UTC, jessyjr97 commented on webapp/src/controlleurs/Controlleurs.php
> +            echo  'success';
Non, vu que c'est Ajax qui va gérer les erreurs. En gros, au lieu de _$result->title_ ou _No data received_, on va mettre les codes d'erreurs de l'API pour que le Ajax côté client puisse afficher un message descriptif avec un code d'erreur.

2019-04-03 14:14 UTC, jessyjr97 commented on webapp/src/controlleurs/Controlleurs.php
>          echo 'il n y a aucune donnee d entree';
Comme mon commentaire ci-dessous, on va faire une meilleure gestion d'erreur qui va être géré côté client pour l'affichage.

2019-04-03 14:15 UTC, jessyjr97 commented on webapp/src/views/OnClick.html
> +            $('#btn_makeAppointment').append('  <span class="fa fa-cog fa-spin"></span>');
Oui, pour espacer la roue qui tourne du message.

2019-04-03 16:36 UTC, yjacques940 requested changes
-Ajouter la localization pour l'onglet rendez-vous

2019-04-03 18:38 UTC, yjacques940 approved these changes

2019-04-03 18:38 UTC, merged