3 ajouter du contenu aux pages statiques
jessyjr97/carlmelanie-masso-webApp pull request #4
Opened 2019-03-20 18:26 UTC by jessyjr97

Ajout du contenu et ajout du système de traduction.
Modèle à suivre dans les fichiers du dossier _lang_:
`{
"Contexte-Title": "Titre de la page / contexte",
"Contexte-Section-Element": "Texte selon la langue choisie"
}`
Et svp garder en ordre alphabétique :)

2019-03-20 19:29 UTC, yjacques940 requested changes

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/controlleurs/Controlleurs.php
> +require('models/ManagerUsers.php');
Ca ne devrait pas plutot être UsersManager en anglais?

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/controlleurs/Controlleurs.php
> +        $userInscript = new ManagerUsers;
UsersManager voir plus haut @NicolasTalbot  Vu que jessy est parti de ta branche, il y a tes modifs dedans. Je vais faire le code review à Jessy, et je vais te tagguer sur les choses que tu travaille pour les modifier et jessy va soit rebase ou les modifier pour que vous ayez les mêmes modifs.

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/controlleurs/Controlleurs.php
> +        $userInscript = new ManagerUsers;
RE: Jessy ne fera pas les modifs, on va pusher comme ca et on mettra les modifs dans ton code review, puis tu rebasera, ca va être plus simple. Il va y avoir quelques conflits, mais ca devrait être assez simple à rebase.

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/css/style.css
> -/* Second, Third and more Tiers
Enlever les commentaires s'ils ne sont pas utilisés

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/css/w3layouts-License.txt
> -/*
Si jamais la cliente décide de payer pour enlever l'Affichage de la licence, il faudra enlever ce fichier peut-être?..

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/lang/fr.json
> +  "About-WhoAreWe": "Qui Nous Sommes",
Qui nous sommes pas de maj au début

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/lang/fr.json
> +  "About-WhoAreWe-Text": "Carl Giguère et Mélanie Plante sont Orthotérapeutes.",
Orthothérapeutes. Il manque un h ;)

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/lang/fr.json
> +  "Home-Text-Details": "Des conditions s'appliques.",
s'appliquent

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/models/Connection.php
> +
PLEIN de lignes vides

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/models/ManagerUsers.php
> +
ligne vide inutile

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/models/ManagerUsers.php
> +
ligne vide inutile

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/models/Connection.php
> +
Connexion = francais, Connection = anglais

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/models/ManagerUsers.php
> +    public function VerifierLogin($email,$password){
Nom en francais , on devrais plutot mettre ValidateLogin ou quelque chose dans le genre

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/views/about.php
> +                <h5><?php echo localize('About-Stats-Certs-Count'); ?></h5>
Certs? je comprend pas trop ce que c'ESt

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/views/footer.php
> +          <h2><a href="index.html">Carl & Mélanie Massothérapie</a></h2>
Orthothérapie

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/views/gabarit.php
> +    <div id="modal01" class="modal" onclick="this.style.display='none'">
peut-être changer le nom du id (Si utilisé)

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/views/home.php
> +          <img src="images/completeLogo.svg" alt="Carl et Mélanie Massothérapie" />
Orthothérapie

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/views/inscription.php
> +          <div class="w3pvt-wls-contact-mid">
Il faudra ajouter la traduction ici @NicolasTalbot  lorsque tua ura rebase sur master

2019-03-20 19:29 UTC, yjacques940 commented on webapp/src/views/shell.php
> +    <title><?php echo $title; ?></title>
Tu pourrais ajouter la localization ici @jessyjr97

2019-03-20 19:43 UTC, yjacques940 commented
BUG @jessyjr97 Lorsqu'on clique sur EN, il y a des tonnes d'Erreurs qui s'affichent. Controller ligne 22.

2019-03-21 12:35 UTC, jessyjr97 commented on webapp/src/controlleurs/Controlleurs.php
> +require('models/ManagerUsers.php');
Sera changé dans la branche à @NicolasTalbot

2019-03-21 12:38 UTC, jessyjr97 commented on webapp/src/css/style.css
> -/* Second, Third and more Tiers
À voir plus tard, vu que ce n'est pas notre code.

2019-03-21 12:38 UTC, jessyjr97 commented on webapp/src/css/w3layouts-License.txt
> -/*
Oui, lorsque la cliente aura payée.

2019-03-21 12:42 UTC, jessyjr97 commented on webapp/src/models/Connection.php
> +
@NicolasTalbot

2019-03-21 12:42 UTC, jessyjr97 commented on webapp/src/models/Connection.php
> +
@NicolasTalbot

2019-03-21 12:42 UTC, jessyjr97 commented on webapp/src/models/ManagerUsers.php
> +
@NicolasTalbot

2019-03-21 12:42 UTC, jessyjr97 commented on webapp/src/models/ManagerUsers.php
> +    public function VerifierLogin($email,$password){
@NicolasTalbot

2019-03-21 12:42 UTC, jessyjr97 commented on webapp/src/models/ManagerUsers.php
> +
@NicolasTalbot

2019-03-21 12:44 UTC, jessyjr97 commented on webapp/src/views/about.php
> +                <h5><?php echo localize('About-Stats-Certs-Count'); ?></h5>
Je ne savais pas comment l'appeler pour les diplômes: Certificates, Diplomas, Qualifications...

2019-03-21 12:45 UTC, jessyjr97 commented on webapp/src/views/footer.php
> +          <h2><a href="index.html">Carl & Mélanie Massothérapie</a></h2>
Fichier inutilisé. À enlever lors du refactoring

2019-03-21 12:46 UTC, jessyjr97 commented on webapp/src/views/gabarit.php
> +    <div id="modal01" class="modal" onclick="this.style.display='none'">
Code provenant du template, donc je ne crois pas pouvoir le modifier à moins de modifier le code du template.

2019-03-21 12:49 UTC, jessyjr97 commented on webapp/src/views/inscription.php
> +          <div class="w3pvt-wls-contact-mid">
### [...] lorsque _tu auras_ rebase [...]

2019-03-21 12:50 UTC, jessyjr97 commented on webapp/src/views/shell.php
> +    <title><?php echo $title; ?></title>
Fichier inutilisé, mais je ne l'ai pas fait dans le vrai gabarit. Je vais le faire dans le prochain commit.

2019-03-21 12:59 UTC, yjacques940 commented on webapp/src/views/footer.php
> +          <h2><a href="index.html">Carl & Mélanie Massothérapie</a></h2>
Créé une autre tache dans ce cas pour ne pas qu'on l'oublie (issue)

2019-03-21 12:59 UTC, yjacques940 approved these changes

2019-03-21 13:00 UTC, merged